#!/usr/bin/env node
// scripts/build-config.js
// Reads env vars (from .env locally, or Vercel Environment Variables in production)
// and writes /config.js which exposes them on window.CABT_CONFIG.
//
// This file is loaded by index.html BEFORE any JSX, so api.jsx can read
// credentials at runtime without them being hardcoded in source.
//
// Run locally:  node scripts/build-config.js
// On Vercel:    runs automatically via vercel.json buildCommand.

const fs = require('fs');
const path = require('path');

// Load .env locally (Vercel injects env vars natively, no .env file needed)
function loadDotEnv() {
  const envPath = path.join(__dirname, '..', '.env');
  if (!fs.existsSync(envPath)) return;
  const lines = fs.readFileSync(envPath, 'utf8').split(/\r?\n/);
  for (const raw of lines) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq < 0) continue;
    const key = line.slice(0, eq).trim();
    let val = line.slice(eq + 1).trim();
    // Strip surrounding quotes
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    if (!(key in process.env)) process.env[key] = val;
  }
}

loadDotEnv();

// Diagnostic: list which SUPABASE_* and VERCEL_* env vars are visible to the
// build process. Helps debug "value set in dashboard but not picked up".
const visible = Object.keys(process.env)
  .filter((k) => k.startsWith('SUPABASE_') || k === 'VERCEL_ENV' || k === 'VERCEL')
  .sort();
console.log('[build-config] env keys visible:', visible.length ? visible.join(', ') : '(none)');
console.log('[build-config] VERCEL_ENV:', process.env.VERCEL_ENV || '(not set)');

const SUPABASE_URL      = process.env.SUPABASE_URL || '';
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || '';
console.log('[build-config] SUPABASE_URL length:', SUPABASE_URL.length);
console.log('[build-config] SUPABASE_ANON_KEY length:', SUPABASE_ANON_KEY.length);

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.error('[build-config] ⚠ Missing SUPABASE_URL or SUPABASE_ANON_KEY.');
  console.error('[build-config]   Local: copy .env.example to .env and fill in.');
  console.error('[build-config]   Vercel: add via Settings → Environment Variables.');
  // Don't fail the build — write an empty config so the page still loads
  // with a clear error instead of breaking the deploy.
}

const out = `// AUTO-GENERATED by scripts/build-config.js — do not edit, do not commit.
// Sourced from .env (local) or Vercel Environment Variables (production).
window.CABT_CONFIG = {
  SUPABASE_URL: ${JSON.stringify(SUPABASE_URL)},
  SUPABASE_ANON_KEY: ${JSON.stringify(SUPABASE_ANON_KEY)}
};
`;

const outPath = path.join(__dirname, '..', 'config.js');
fs.writeFileSync(outPath, out, 'utf8');
console.log('[build-config] ✓ wrote config.js (' + out.length + ' bytes)');
console.log('[build-config]   SUPABASE_URL:      ' + (SUPABASE_URL ? '✓ set' : '✗ MISSING'));
console.log('[build-config]   SUPABASE_ANON_KEY: ' + (SUPABASE_ANON_KEY ? '✓ set' : '✗ MISSING'));

// ── PWA version stamping ───────────────────────────────────────────────────
// Bobby 2026-05-05: "When I save a new version to my desktop it does not show
// the updates." Root cause was a stale VERSION in service-worker.js, which
// the browser uses to decide whether to reinstall the SW + re-cache the app
// shell. Now stamped automatically on every Vercel build (or whenever this
// script runs) so installed PWAs detect new builds without any manual step.
//
// Prefer Vercel's deploy SHA when available (stable per deploy, distinct per
// commit); fall back to current Unix timestamp for local dev runs.
const VERCEL_SHA = process.env.VERCEL_GIT_COMMIT_SHA || '';
const stamp = VERCEL_SHA ? VERCEL_SHA.slice(0, 12) : String(Math.floor(Date.now() / 1000));

const swPath  = path.join(__dirname, '..', 'service-worker.js');
const idxPath = path.join(__dirname, '..', 'index.html');

try {
  let sw = fs.readFileSync(swPath, 'utf8');
  const before = sw;
  sw = sw.replace(/^const VERSION = '[^']+';/m, `const VERSION = '${stamp}';`);
  if (sw !== before) {
    fs.writeFileSync(swPath, sw, 'utf8');
    console.log('[build-config] ✓ stamped service-worker.js VERSION = ' + stamp);
  } else {
    console.warn('[build-config] ⚠ service-worker.js: VERSION line not found, skipped stamp');
  }
} catch (e) {
  console.warn('[build-config] ⚠ could not stamp service-worker.js:', e.message);
}

try {
  let idx = fs.readFileSync(idxPath, 'utf8');
  const before = idx;
  idx = idx.replace(/(<!-- PWA · injected by scripts\/build-pwa\.sh · build )[^ ]+( -->)/, `$1${stamp}$2`);
  idx = idx.replace(/(window\.CABT_BUILD = ')[^']+(';)/, `$1${stamp}$2`);
  if (idx !== before) {
    fs.writeFileSync(idxPath, idx, 'utf8');
    console.log('[build-config] ✓ stamped index.html build = ' + stamp);
  } else {
    console.warn('[build-config] ⚠ index.html: build markers not found, skipped stamp');
  }
} catch (e) {
  console.warn('[build-config] ⚠ could not stamp index.html:', e.message);
}
